# workflowr_commands_spei_thesis.R

# to figure out how to get a pre-existing RStudio project into workflowr, I git forked and fit cloned your GitHub SPEI_thesis repository
# this allowed me to make changes to it without changing the original version
# I could only do this because you had given me access permission

# I got it to work, but it is admittedly a bit glitchy, especially pusing it to GitHub

# in this file, I included all the steps I used to get it setup with some explanation,
# theoretically, you should be able to run these commands and get this setup in for your version of the SPEI_thesis repository

# these commands are used to setup workflowr project in an existing directory structure (as opposed to creating a brand new project with Git in RStudio)

# relevant packages
library(workflowr)
library(rmarkdown)

# in your laptop's SPEI_thesis folder, add a subfolder called "analysis", which is required by workflowr and is where all RMarkdown files are saved (for this analysis and any others)
# as per https://jdblischak.github.io/workflowrBeta/articles/wflow-03-migrating.html
dir.create("analysis")

# create an object with the working directory path (the current analysis needs to be part of an existing RStudio project)
wd <- getwd()

# the wflow_start command creates files that workflowr uses to build the html file for the GitHub website, including a "docs" folder that has the html files for the GitHub webpage
wflow_start(wd, existing = TRUE, git = FALSE) # only run this once, this project is already setup with Git, so set git to FALSE

# create/open an RMarkdown file for the nest survival analysis (if the RMarkdown file with this file name doesn't exist, this command will create it, otherwise it will open the file in RStudio)
wflow_open("analysis/fit_nest_survival.Rmd") # note the Rmarkdown file is in the analysis folder, as required by workflowr

# in the Rmarkdown file, I cut and pasted in the code from the current nest survival Rscript file
# in RMark down, R script that gets run goes between this:
#```{r}
#and this (remove the # that made those a comment)
#```

# between the code chunks, you can add text, for example to explain what the previous code is for, discuss the results and include output from that code, etc.
# look at the fit_nest_survival.Rmd file in my copy of your repository as an example
# basics of RMarkdown: https://rmarkdown.rstudio.com/lesson-1.html

# you can also just use the version of "fit_nest_survival.Rmd" that is in my version of your SPEI_thesis repository, it's in the "analysis" folder

# run the RMarkdown file for nest survival
# Before I run the command that follows (wflow_build), I usually highlight and run each code chunk in the Rmarkdown file first (select "run selected lines" from "run" menu in upper right), before running (ie "knitting") the whole file
# once you are sure each code chunk works, run this to test the whole file:
wflow_build("analysis/fit_nest_survival.Rmd")
# you have to close all the text files with output that RMark generates to get the wflow_build command to finish

# to commit using workflowr, you have to specify info on your account 
wflow_use_github("DJRIZZ") # use your GitHub user name
wflow_git_config(user.name = "DJRIZZ", user.email = "djrizzolo@alaska.edu", overwrite = TRUE)

# to commit this version of the RMarkdown file to Git using workflowr, use the wflow_publish command
# Workflowr uses the term "publish" for commit 
# publish/commit files individually to have file-specific commit comments
# publishing/committing re-runs the Rmd files
# the wflow_publish command runs the RMarkdown script again and commits it to the local Git
# you have to commit all the files workflowr uses to buld the website *license, about, and index html files) in addition to your RMarkdown file
# if you want, you can edit thse files first by opening them using the wflow_open command
wflow_publish("analysis/license.Rmd", "initial commit")
wflow_publish("analysis/about.Rmd", "initial commit")
wflow_publish("analysis/index.Rmd", "updated with link to nest survival analysis")
wflow_publish("analysis/fit_nest_survival.Rmd", "made nest survival anaylsis a workflowr project")
# close text windows generated by RMark for the nest survival RMarkdown file to finish

# all of the versions of all of the above files are not committed to Git
# when you make changes to any of them, run the wflow_publish command for that file with a descriptive comment to update it in Git

# the wflow_git_push() command to sed files to GitHub is very glitchy and has never worked for me

# I use Git Bash or Git CMD to push file directly from the SPEI_thesis directory
# Once I have the Git Bash or Git CMD prompt in the SPEI_thesis folder, I run this command to push the files: 
# git push -u origin

# after you have pushed files to your GitHub, you have to make a few changes to the settings for the SPEI_thesis respository on GitHub
# on your GitHub account, in the SPEI_thesis repository
# goto settings
# make repository public
# goto Pages (on left menu)
# set source =deploy from branch
# set branch = main

# the GitHub project webpage URL is  https://{userid}.github.io/{reponame}
# for my test version, it's: https://DJRIZZ.github.io/SPEI_thesis

# NOTE that the repository has to be public to make a webpage
# if you don't want copies of your data files on GitHub before you have published your results
# add csv files to your .gitignore file by adding ".csv" to the ignore list (which by defualt includes .Rproj.user and 3 other file types), 
# or delete those folders from GitHub

